---
settings:
  name: Azure NetApp Files
  release_notes_autogen:
    release_notes_repo: console-relnotes
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentazione Azure NetApp Files
    url: "/index.html"
  - title: Note di rilascio
    entries:
    - title: Cosa c'è di nuovo
      url: "/whats-new.html"
  - title: Iniziare
    entries:
    - title: Scopri di più su Azure NetApp Files
      url: "/concept-azure-netapp-files.html"
    - title: Flusso di lavoro introduttivo
      url: "/task-quick-start.html"
    - title: Configurare un'applicazione Microsoft Entra
      url: "/task-set-up-azure-ad.html"
    - title: Creare un sistema
      url: "/task-create-system.html"
  - title: Utilizzare Azure NetApp Files
    entries:
    - title: Crea e monta volumi
      url: "/task-create-volumes.html"
    - title: Gestire i volumi esistenti
      url: "/task-manage-volumes.html"
    - title: Rimuovere i Azure NetApp Files
      url: "/task-remove-system.html"
  - title: Conoscenza e supporto
    entries:
    - title: Registrati per ricevere supporto
      url: "/task-support-registration.html"
    - title: Ottieni aiuto
      url: "/task-get-help.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: Storage Management
  repo: storage-management-family
